---
- hosts: all
  tasks:
    - name: install httpd
      package: name=httpd state=installed
    - name: configure
      #shell: "echo Hello World!!! > /var/www/html/index.html"
      shell: "echo -e '<html>\n<html>\n\t<body>\n\t\t<h1>Hello World! .......</h1>\n\t</body>\n</html>' > /var/www/html/index.html"
    - name: start service
      service: name=httpd state=started
    - name: add user
      user: name=raman state=present
